stages:
- build
- test
- deploy
########################################################################################################################
####START####                                     PROJECT LEVEL VARIABLES                                  ####START####
########################################################################################################################
variables:
  VERSION: 0.1.0b
  BITSUM_CLI_LINUX: Bitsum-CLI-Linux-v${VERSION}.tar.gz
  BITSUM_CLI_WINDOWS: Bitsum-CLI-Windows-v${VERSION}.zip
  BITSUM_CLI_MACOS: Bitsum-CLI-MacOS-v${VERSION}.tar.gz
  DOWNSTREAM_AGAMA_BRANCH: ${CI_COMMIT_REF_NAME}
  POST_MESSAGE: "Source: ${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}\n
  Pipeline Trigger: ${CI_PIPELINE_SOURCE}\n
  Commit: ${CI_COMMIT_SHA}$\n
  ${CI_COMMIT_MESSAGE}"
########################################################################################################################
####END####                                        PROJECT LEVEL VARIABLES                                   ####END####
########################################################################################################################
########################################################################################################################
########################################################################################################################
####START####          Build Stage: compile and package komodo binaries for Bitsum CLI                     ####START#####
########################################################################################################################
########################################################################################################################
####START####                                            LINUX                                             ####START####
########################################################################################################################
build:linux:
  image: asherd/bitsum-builders:bitsum-ubuntu
  variables:
    DOCKER_DRIVER: overlay2
  stage: build
  cache:
    key: "${CI_JOB_NAME}${CI_COMMIT_REF_NAME}"
    paths:
    - depends/built
  script:
  - zcutil/build.sh -j$(nproc)
  - mkdir bitsum-cli
  - cp src/komodod
      src/komodo-cli
      src/fiat/bitsum
      src/bitsumd
      doc/man/bitsum-cli/linux/README.txt
      zcutil/fetch-params.sh
      bitsum-cli
  - mv bitsum-cli/fetch-params.sh bitsum-cli/fetch-params
  - chmod +x bitsum-cli/komodod
  - chmod +x bitsum-cli/komodo-cli
  - chmod +x bitsum-cli/bitsum
  - chmod +x bitsum-cli/bitsumd
  - chmod +x bitsum-cli/fetch-params
  - if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then strip -g bitsum-cli/komodod && strip -g bitsum-cli/komodod; fi
  - tar -czvf ${BITSUM_CLI_LINUX} bitsum-cli
  - md5sum ${BITSUM_CLI_LINUX} > ${BITSUM_CLI_LINUX}.md5
  - curl -F file=@"${BITSUM_CLI_LINUX}"
      -F channels="${CLI_POST_CHANNEL}"
      -F initial_comment="${POST_MESSAGE}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
    - ${BITSUM_CLI_LINUX}
    - ${BITSUM_CLI_LINUX}.md5
    expire_in: 1 week
########################################################################################################################
####END####                                              LINUX                                               ####END####
########################################################################################################################
####START####                                           WINDOWS                                            ####START####
########################################################################################################################
build:windows:
  image: asherd/bitsum-builders:bitsum-windows
  variables:
    DOCKER_DRIVER: overlay2
  stage: build
  cache:
    key: "${CI_JOB_NAME}${CI_COMMIT_REF_NAME}"
    paths:
    - depends/built
  script:
  - zcutil/build-win.sh -j$(nproc)
  - mkdir bitsum-cli
  - cp src/komodod.exe
      src/komodo-cli.exe
      src/komodo-tx.exe
      src/fiat/bitsum.bat
      src/bitsumd.bat
      doc/man/bitsum-cli/windows/README.txt
      zcutil/fetch-params.bat
      zcutil/wget64.exe
      bitsum-cli
  - zip -r ${BITSUM_CLI_WINDOWS} bitsum-cli
  - md5sum ${BITSUM_CLI_WINDOWS} > ${BITSUM_CLI_WINDOWS}.md5
  - curl -F file=@"${BITSUM_CLI_WINDOWS}"
      -F channels="${CLI_POST_CHANNEL}"
      -F initial_comment="${POST_MESSAGE}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
    - ${BITSUM_CLI_WINDOWS}
    - ${BITSUM_CLI_WINDOWS}.md5
    expire_in: 1 week
########################################################################################################################
####END####                                             WINDOWS                                              ####END####
########################################################################################################################
####START####                                            MACOS                                             ####START####
########################################################################################################################
build:mac:
  stage: build
  tags: ["High Sierra"]
  cache:
    key: "${CI_JOB_NAME}${CI_COMMIT_REF_NAME}"
    paths:
    - depends/built
  script:
  - zcutil/build-mac.sh -j$(sysctl -n hw.physicalcpu)
  - ./makeReleaseMac.sh
  - tar -czvf ${BITSUM_CLI_MACOS} bitsum-cli
  - md5sum ${BITSUM_CLI_MACOS} > ${BITSUM_CLI_MACOS}.md5
  - curl -F file=@"${BITSUM_CLI_MACOS}"
      -F channels="${CLI_POST_CHANNEL}"
      -F initial_comment="${POST_MESSAGE}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
    - ${BITSUM_CLI_MACOS}
    - ${BITSUM_CLI_MACOS}.md5
    expire_in: 1 week
########################################################################################################################
####END####                                              MACOS                                               ####END####
########################################################################################################################
########################################################################################################################
####END####                                           Build Stage                                            ####END####
########################################################################################################################
########################################################################################################################
########################################################################################################################
########################################################################################################################
####START####     Test stage: Test functionality of komodo binaries. Produce code quality and SAST reports. ####START####
########################################################################################################################
########################################################################################################################
########################################################################################################################
####START####                                        Code Quality                                          ####START####
########################################################################################################################
.code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
  - docker:stable-dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
########################################################################################################################
####END####                                          Code Quality                                            ####END####
########################################################################################################################
########################################################################################################################
####START####                              Static Application Security Tests                               ####START####
########################################################################################################################
.sast:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
  - docker:stable-dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
      --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
      --volume "$PWD:/code"
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    paths: [gl-sast-report.json]
########################################################################################################################
####END####                                Static Application Security Tests                                 ####END####
########################################################################################################################
########################################################################################################################
####START####                            Run Bitsum CLI on Ubuntu Xenial (16.04)                            ####START####
########################################################################################################################
.ubuntu:xenial:
  image: ubuntu:xenial
  variables:
    DOCKER_DRIVER: overlay2
  stage: test
  before_script:
  - apt update && apt install -y wget libgomp1 libcurl4-gnutls-dev python
  - rm -rf /root/.komodo || true
  - mv .komodo /root/ || true
  script:
  - tar -xzvf ${BITSUM_CLI_LINUX}
  - export PATH=$PATH:$CI_PROJECT_DIR/bitsum-cli
  - python qa/bitsum-cli-tests/bitsum-cli-tester.py
  after_script:
  - mv /root/.komodo ./ || true
  cache:
    key: ${CI_JOB_NAME}
    paths: [.komodo]
  artifacts:
    paths: [log.txt]
    expire_in: 1 week
  dependencies:
  - build:linux
########################################################################################################################
####END####                               Run Bitsum CLI on Ubuntu Xenial (16.04)                             ####END####
########################################################################################################################
########################################################################################################################
####START####                             Run Bitsum CLI on Ubuntu Bionic (18.04)                           ####START####
########################################################################################################################
.ubuntu:bionic:
  image: ubuntu:bionic
  variables:
    DOCKER_DRIVER: overlay2
  stage: test
  before_script:
  - apt update && apt install -y wget libgomp1 libcurl4-gnutls-dev python
  - rm -rf /root/.komodo || true
  - mv .komodo /root/ || true
  script:
  - tar -xzvf ${BITSUM_CLI_LINUX}
  - export PATH=$PATH:$CI_PROJECT_DIR/bitsum-cli
  - python qa/bitsum-cli-tests/bitsum-cli-tester.py
  after_script:
  - mv /root/.komodo ./ || true
  cache:
    key: ${CI_JOB_NAME}
    paths: [.komodo]
  artifacts:
    paths: [log.txt]
    expire_in: 1 week
  dependencies:
  - build:linux
########################################################################################################################
####END####                               Run Bitsum CLI on Ubuntu Bionic (18.04)                             ####END####
########################################################################################################################
########################################################################################################################
####START####                             Run Bitsum CLI on MacOS Sierra (10.12.6)                          ####START####
########################################################################################################################
.macos:sierra:
  stage: test
  tags: ["Sierra"]
  script:
  - tar -xzvf $BITSUM_CLI_MACOS
  - export PATH=$PATH:$CI_PROJECT_DIR/bitsum-cli
  - python qa/bitsum-cli-tests/bitsum-cli-tester.py
  artifacts:
    paths: [log.txt]
    expire_in: 1 week
  dependencies:
  - build:mac
########################################################################################################################
####END####                               Run Bitsum CLI on MacOS Sierra (10.12.6)                            ####END####
########################################################################################################################
########################################################################################################################
####START####                          Run Bitsum CLI on MacOS High Sierra (10.12.6)                        ####START####
########################################################################################################################
.macos:high-sierra:
  stage: test
  tags: ["High Sierra"]
  script:
  - tar -xzvf ${BITSUM_CLI_MACOS}
  - export PATH=$PATH:$CI_PROJECT_DIR/bitsum-cli
  - python qa/bitsum-cli-tests/bitsum-cli-tester.py
  artifacts:
    paths: [log.txt]
    expire_in: 1 week
  dependencies:
  - build:mac
########################################################################################################################
####START####                          Run Bitsum CLI on MacOS High Sierra (10.12.6)                        ####START####
########################################################################################################################
########################################################################################################################
####START####                              Run Bitsum CLI on Windows 10                                     ####START####
########################################################################################################################
.windows:10:
  stage: test
  tags: ["Windows 10"]
  script:
  - PowerShell Expand-Archive -Path %BITSUM_CLI_WINDOWS% -DestinationPath %CI_PROJECT_DIR%
  - set PATH=%PATH%;%CI_PROJECT_DIR%\bitsum-cli
  - qa\bitsum-cli-tests\bitsum-cli-tester.py
  artifacts:
    paths: [log.txt]
    expire_in: 1 week
  dependencies:
  - build:windows
########################################################################################################################
####END####                                Run Bitsum CLI on Windows 10                                       ####END####
########################################################################################################################
########################################################################################################################
####END####                                           Test Stage                                             ####END####
########################################################################################################################
########################################################################################################################
####START####                                         Deploy                                               ####START####
########################################################################################################################
deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  variables:
    DOCKER_DRIVER: overlay2
  dependencies:
  - build:linux
  - build:windows
  - build:mac
  script:
  - mkdir Windows && mkdir Linux && mkdir MacOS &&
    mv ${BITSUM_CLI_WINDOWS} Windows &&
    mv ${BITSUM_CLI_LINUX} Linux &&
    mv ${BITSUM_CLI_MACOS} MacOS
  - echo "$AUTH_KEY" > AUTH_KEY.json &&
    gcloud auth activate-service-account
    --key-file AUTH_KEY.json
  - gsutil cp -r Windows Linux MacOS $STAGING/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}/
  - curl -X POST
      -F token="$CI_JOB_TOKEN"
      -F ref="$DOWNSTREAM_AGAMA_BRANCH"
      -F variables\[UPSTREAM_TRIGGER_INFO\]="${POST_MESSAGE}"
      -F variables\[BITSUM_CLI_LINUX\]="${BITSUM_CLI_LINUX}"
      -F variables\[BITSUM_CLI_WINDOWS\]="${BITSUM_CLI_WINDOWS}"
      -F variables\[BITSUM_CLI_MACOS\]="${BITSUM_CLI_MACOS}"
      "https://gitlab.com/api/v4/projects/8018592/trigger/pipeline"
########################################################################################################################
####END####                                           Deploy                                                 ####END####
########################################################################################################################
